version: '3.8'

services:
  backend: 
    build: ./backend
    ports: 
      - '8080:8080'
    depends_on:
      - db

  db:
    image: 'postgres'
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=docker
      - POSTGRES_DB=react_query_demo_db
    volumes: 
      - data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    volumes:
      - ../app/data/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  data: